services:
  mock-google-stt-service:
    build:
      context: .
      dockerfile: Dockerfile.mock
    ports:
      - "5002:5000"
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 