version: '3.8'

services:
  google-stt-service:
    build: .
    ports:
      - "5001:5000"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials/service-account-key.json
    volumes:
      - ./credentials:/app/credentials:ro
      - ./uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 